client:
  - clientName: client1
    endpoint: 192.168.0.251:32000
    accessKeyID: minio
    secretAccessKey: minio123
    secure: false
    clientType: minio
cache:
  - cacheName: cache1
    cacheType: redis
    cacheServerEndpoint: 127.0.0.1:6379